web/grader/urls.py
from django.urls import path

from . import views

app_name = 'grader'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:task_name>/desc', views.desc, name='desc'),
    path('submit/', views.submit, name='submit'),
    path('submission/', views.submission, name='submission'),
    path('submission/<int:page>/', views.submission, name='submission'),
    path('submission_code/<int:sub_id>/', views.submission_code, name='submission_code'),
    path('submission_code/<int:sub_id>/<int:page>/', views.submission_code, name='submission_code'),
    path('submission/user/<str:username>/', views.submission_user, name='submission_user'),
    path('submission/user/<str:username>/<int:page>/', views.submission_user, name='submission_user'),
    path('submission/task/<str:taskname>/', views.submission_task, name='submission_task'),
    path('submission/task/<str:taskname>/<int:page>/', views.submission_task, name='submission_task'),
]

web/tle/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('grader.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

web/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

web/grader/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    name = models.CharField(max_length = 128, unique = True)
    desc = models.CharField(max_length = 256)
    time = models.IntegerField()
    mem = models.IntegerField()

class Submission(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    task = models.ForeignKey(Task, on_delete=models.PROTECT)
    status = models.CharField(max_length = 64, null = True)
    result = models.CharField(max_length = 64, null = True)
    score = models.IntegerField(null = True)
    submitted_at = models.DateTimeField()
    time_used_ms = models.IntegerField(null = True)
    mem_used_kb = models.IntegerField(null = True)

web/grader/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage
from django.http import HttpResponse
from django.views.static import serve
from django.shortcuts import render, redirect
from django.template import loader
from django import forms
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
import codecs
import sys


import datetime

from .grade import grade
from .models import Task, Submission

from threading import Thread
import os

SUBMISSION_PATH = os.getenv('TLE_DATA_PATH') + '/submissions'
TASK_PATH = os.getenv('TLE_TASKS_PATH')

def index(request):
    tasks = Task.objects.all().order_by('-id')
    ts = []

    if request.user.is_authenticated:
        for task in tasks:
            submissions = Submission.objects.filter(author = request.user,
                                        task = task).order_by('-id')
            ts.append((task, submissions.first()))
    else:
        for task in tasks:
            ts.append((task, None))

    context = { 'task_list': ts }
    return render(request, 'index.html', context)

PER_PAGE = 10

def submission0(request, page = 1, username = None, taskname = None):
    msg = ''

    if username is not None:
        submissions = Submission.objects.filter(author = User.objects.get(username = username)).order_by('-id')
        msg = f'for user {username}'
    elif taskname is not None:
        submissions = Submission.objects.filter(task = Task.objects.get(name = taskname)).order_by('-id')
        msg = f'for task {taskname}'
    else:
        submissions = Submission.objects.all().order_by('-id')
    

    paginator = Paginator(submissions, PER_PAGE)
    try:
        page_o = paginator.page(page)
    except EmptyPage:
        return index(request)

    return render(request, 'submission.html', {
        'submission_list': page_o,
        'msg': msg,
        'page' : page
    })

def submission(request, page = 1):
    return submission0(request, page)

def submission_task(request, taskname, page = 1):
    return submission0(request, page, taskname = taskname)

def submission_user(request, username, page = 1):
    return submission0(request, page, username = username)

def desc(request, task_name):
    t = Task.objects.get(name = task_name)
    filepath = f'{TASK_PATH}/{task_name}/{t.desc}'
    return serve(request, os.path.basename(filepath), os.path.dirname(filepath))


def check_admin(user):
   return user.is_superuser

@user_passes_test(check_admin)
def submission_code(request, sub_id):
    code_file = None
    for f in os.listdir(f'{SUBMISSION_PATH}/{sub_id}'):
        if f.endswith('.cxx'):
            code_file = f'{sub_id}/{f}'
            break

    print(f'{os.path.basename(code_file)}, {os.path.dirname(code_file)}')

    if code_file is not None:
        return serve(request, code_file, SUBMISSION_PATH)

class SubmitForm(forms.Form):
    task_id = forms.CharField(label="Task ID", max_length=100)
    file = forms.FileField()

@login_required
def submit(request):
    if request.method == 'POST':
        form = SubmitForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            print(data)

            task_id = int(data['task_id'])
            task = Task.objects.get(id = task_id)
            print(task)

            submission = Submission.objects.create(author = request.user,
                                    task = task,
                                    submitted_at = datetime.datetime.now())


            file = request.FILES['file']
            code = file.read().decode('utf-8')

            Thread(target = grade,
                   args = (task.name, code, submission.id, )).start()

            messages.success(request, (f'Submitted {task.name}'))
            return redirect('/')
    else:
        form = SubmitForm()

    return render(request, 'submit.html', {'form': form})

web/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.static import serve
from django.shortcuts import render
from django.template import loader
import django.contrib.auth as auth
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages

def login2(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.success(request, ("There was an error logging in"))
            return redirect('login')
    else:
        return render(request, 'login.html', {})

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username = username, password = password)
            auth.login(request, user)
            messages.success(request, ('Login successful'))
            return redirect('/')
        else:
            messages.error(request, ("There was an error logging in"))
    else:
        form = AuthenticationForm()

    return render(request, 'login.html', { 'form': form }) 

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = request.POST['username']
            password = request.POST['password1']
            user = auth.authenticate(username = username, password = password)
            auth.login(request, user)
            messages.success(request, ('Registered successfully'))
            return redirect('/')
    else:
        form = UserCreationForm()

    return render(request, 'register.html', { 'form': form }) 

def logout(request):
    auth.logout(request)
    messages.success(request, ('Logged out'))
    return redirect('login')

web/grader/templates/index.html
{% extends 'base.html' %}

{% block title %}Grader Dashboard{% endblock %}

{% block header %}
<h3>Grader UwU</h3>
<p><a href="{% url 'grader:submit' %}">Submit</a></p>
<p><a href="{% url 'grader:submission' 1 %}">Submission</a></p>
{% endblock %}

{% block body %}

<table>
    <thead>
    <tr>
        <th>#</th>
        <th>Name</th>
        <th></th>
        {% if user.is_authenticated %}
        <th>Result</th>
        {% endif %}
    </tr>
    </thead>
{% if task_list %}
    <tbody>
    {% for task, sub in task_list %}
    <tr>
        <td>{{task.id}}</td>
        <td><a href="{% url 'grader:desc' task.name %}">{{task.name}}</a></td>
        <td>{{task.time}}ms - {{task.mem}}kb</td>
        {% if sub %}
        <td>score: {{sub.score}} [{{sub.result}}]</td>
        {% endif %}
    </tr>
    {% endfor %}
    </tbody>
{% else %}
    <p>No tasks are available.</p>
{% endif %}

{% endblock %}



{% block footer %}
{% if user.is_authenticated %}
<a href="{% url 'users:logout' %}">Logout</a>
{% else %}
<a href="{% url 'users:login' %}">Login</a>
{% endif %}
{% endblock %}

web/grader/templates/submission.html
{% extends 'base.html' %}

{% block title %}Grader Submission{% endblock %}

{% block header %}
<h3>Submission page {{page}}
	{% if msg != None %} {{msg}} {% endif %}</h3>
<a href="{% url 'grader:index' %}">Home</a>
{% endblock %}

{% block body %}

<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>DateTime</th>
        <th>User</th>
        <th>Task</th>
        <th>Result</th>
        <th>Score</th>
        <th>Time (ms)</th>
        <th>Mem (kb)</th>
    </tr>
    </thead>
{% if submission_list %}
    <tbody>
    {% for s in submission_list %}
    <tr class="task">
        <td><a href="{% url 'grader:submission_code' s.id %}">{{s.id}}</a></td>
        <td>{{s.submitted_at|date:"d/m/y"}} {{s.submitted_at|time:"H:i"}}</td>
        <td><a href="{% url 'grader:submission_user' s.author.username %}">{{s.author.username}}</a></td>
        <td><a href="{% url 'grader:submission_task' s.task.name %}">{{s.task.name}}</a></td>
        <td>{{s.result}}</td>
        <td>{{s.score}}</td>
        <td>{{s.time_used_ms}}</td>
        <td>{{s.mem_used_kb}}</td>
    </tr>
    {% endfor %}
    </tbody>
{% else %}
    <p>No submissions.</p>
{% endif %}

{% endblock %}

web/grader/templates/submit.html
{% extends 'base.html' %}

{% block title %}Submit{% endblock %}

{% block header %}
<h3>Submit<h3>
{% endblock %}

{% block body %}

<form method="POST" action="{% url 'grader:submit'%}"
    enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

web/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        {% block styles  %}
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://fonts.xz.style/serve/inter.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
        {% endblock %}
        {% block scripts %}
        
        {% endblock %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="description" content="{% block meta_desc %}{% endblock %}" />
        <meta name="keywords" content="{% block meta_keywords %}{% endblock %}" />
        {% block head_rest %}{% endblock %}
    </head>    

    <body>
        <div class="container ">
            <div>
                <div id="main_header" style="padding: 1rem 0;">
                    {% block header %}{% endblock %}

                    {% if form.errors %}
                    <p>There was errors with your form...</p>
                    {% for field, errors in form.errors.items %}
                        {% for err in errors %}
                        {{ err }}
                        {% endfor %}
                    {% endfor %}
                    {% endif %}

                    {% if messages %}
                    <ul>
                        {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                            {{ message }}
                        </li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div id="main_body">
                    {% block body %}
                    {% endblock %}
                </div>

                <div id="main_footer">
                    {% block footer %}{% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

web/users/templates/login.html
{% extends 'base.html' %}


{% block header %}
<h3>Grader Login</h3>
<a href="{% url 'users:register' %}">No account? register</a>
{% endblock %}

{% block body %}

  <form method="POST" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
  </form>

{% endblock %}

web/users/templates/register.html
{% extends 'base.html' %}

{% block header %}
<h3>Grader Register</h3>
<a href="{% url 'users:login' %}">Login</a>
{% endblock %}

{% block body %}

  <form method="POST" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
  </form>

{% endblock %}